РК1
java-park-mail-ru/RHA-02-2018 pull request #1
Opened 2018-02-28 17:28 UTC by HimmelSpark

2018-02-28 18:23 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/models/User.java
> +//    public void setUsername(String username) {
?

2018-02-28 18:23 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/services/UserService.java
> +//    public static Boolean exists(User user) {
?

2018-02-28 18:23 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/servlets/AuthServlet.java
> +public class AuthServlet extends javax.servlet.http.HttpServlet {
?

2018-02-28 20:00 UTC, Badya requested changes

2018-02-28 20:00 UTC, Badya commented on README.md
> +  name: "vasya",
Оно не зря красным горит)

2018-02-28 20:00 UTC, Badya commented on pom.xml
> +		<java.version>1.8</java.version>
Java 9

2018-02-28 20:00 UTC, Badya commented on pom.xml
> +			<artifactId>spring-boot-starter-web</artifactId>
зачем и стартер и стартер-веб ?

2018-02-28 20:00 UTC, Badya commented on pom.xml
> +			<version>1.5.10.RELEASE</version>
Версия должна браться из parent

2018-02-28 20:00 UTC, Badya commented on src/main/java/com/gameapi/rha/controller/UserController.java
> +    private static String  SUCCESSFULLY_REGISTERED = "10";
use enum

2018-02-28 20:00 UTC, Badya commented on src/main/java/com/gameapi/rha/models/Password.java
> +    public static String getSaltedHash(String password) throws NoSuchAlgorithmException,InvalidKeySpecException {
Похэндлите эти эксепшны тут - зачем их выбрасывать?

2018-02-28 20:00 UTC, Badya commented on src/main/java/com/gameapi/rha/services/UserService.java
> +    public static User create(User user) {
Метод create возвращающий user и требующий user %)

2018-02-28 20:00 UTC, Badya commented on src/test/java/com/gameapi/rha/RhaApplicationTests.java
> +	public void contextLoads() {
Тесты это хорошо, но в данном случае странно

2018-03-01 09:47 UTC, Badya requested changes

2018-03-01 09:47 UTC, Badya commented on pom.xml
> +			<!--<version>1.5.10.RELEASE</version>-->
комменты зачем оставлять?

2018-03-01 11:55 UTC, Badya requested changes

2018-03-01 11:55 UTC, Badya commented on src/main/java/com/gameapi/rha/controller/UserController.java
> +    private static String  SUCCESSFULLY_REGISTERED = "10";
use enum

2018-03-05 20:27 UTC, Badya requested changes

2018-03-05 20:27 UTC, Badya commented on pom.xml
> +		<version>1.5.10.RELEASE</version>
Boot 2

2018-03-05 20:27 UTC, Badya commented on src/main/java/com/gameapi/rha/controller/UserController.java
> +    private enum UserStatus {
Можно выташить из контроллера отдельно

2018-03-05 20:27 UTC, Badya commented on src/main/java/com/gameapi/rha/controller/UserController.java
> +@CrossOrigin(origins = "http://bf-balance.herokuapp.com")
сделать параметром

2018-03-05 20:27 UTC, Badya commented on src/main/java/com/gameapi/rha/controller/UserController.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN).body(UserStatus.ALREADY_AUTHENTICATED);
Будет ли это JSON?

2018-03-06 16:42 UTC, HimmelSpark commented on pom.xml
> +		<version>1.5.10.RELEASE</version>
В связке Boot2 Java9 проверку на Travis не проходит

2018-03-12 11:42 UTC, Badya commented
Checkstyle?

2018-03-29 20:29 UTC, Badya requested changes
уберите комменты из кода
джава 9

2018-04-01 17:54 UTC, BritikovKI commented
Ну вроде как дофиксили.

2018-04-04 19:50 UTC, merged