РК2
java-park-mail-ru/RHA-02-2018 pull request #2
Opened 2018-04-04 20:54 UTC by BritikovKI

БД на jdbc+ тесты

2018-04-06 14:28 UTC, isopov commented
- мавеном тесты не запускаются - посмотрите на https://github.com/java-park-mail-ru/samples/blob/master/sample-2-1/pom.xml#L93
- `@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)` - с реальным Http-сервером на конкретном порту - это слишком сильная зависимость от окружения, которая имеет смысл, как меньшее зло, только в очень legacy проектах.
- testng - я не против, если вы будете делать тесты на нем, но тогда уж только на нем - либо его удалите, либо junit
- `DROP SMTH IF EXISTS`, `CREATE SMTH IF NOT EXISTS` - в миграциях такого быть не должно, весь смысл как раз в том, чтобы мы полностью контроллировали что уже было в базе, что мы туда добавляем и падали при любом несовпадении.
- `flyway-maven-plugin` - вам не нужен - миграции будут запускаться при старте приложения, и этого достаточно. С этим возникли какие-то проблемы? (Виже закомментированный flyway-core)
- `spring-boot-starter-web-services` - а это вам зачем? 
- При использовании бута и его управления версиями, такое нужно снабжать комментариями, зачем оно нужно и когда нужно поменять/удалить
```
        <hibernate.version>5.2.1.Final</hibernate.version>
        <c3p0.version>0.9.5.2</c3p0.version>
```
- Эта комбинация не работает:
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
@Transactional
```
- `Password` - хороший класс, но оставьте лучше хеширование паролей и вообще безопасность в реальных проектах тем людям, для которых это дело всей жизни. Шифрование паролей лучше сделать как-то так - https://park.mail.ru/blog/topic/view/7197/
- `UserControllerTest` - не увидел теста на happy path - то есть успешную регистрацию и успешный логин. А это самое важное - всегда лучше начинать с happy path, а потом переходить к нестандартным случаям.

2018-04-06 14:34 UTC, isopov requested changes
Замечания в комментарии.

2018-04-19 09:42 UTC, BritikovKI commented
Вроде были внесены все востребованные правки. Done!(i think so)

2018-04-19 16:35 UTC, isopov commented
- testng остался
- spring-boot-test с compile-scope (c Тестовым scope) он тянется через spring-boot-starter-test
- junit у вас и 4, и 5-ой версии и в зависимостях, и используются - удалите один (junit5 оставьте, как у нас во всех примерах)

2018-04-20 18:40 UTC, BritikovKI commented
По поводу codestyle: от нас на первом РК попросили подключить чекстайл, он импортится в Идею как плагин и их есть два типа: гугловский и sun, он же в свою очередь ругается как на отсутствие комментариев, так и на пробелы и отступы, если это критично, я могу это пофиксить и убрать чекстайл, так как на самом деле я переделывал изначальный вид кода(он был попроще и поближе к Си)

2018-04-26 17:31 UTC, isopov commented
`private PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();` - в классе User - это всё еще не passwordEncoder из контеста.

Про форматирование - нужно один раз настроить форматтер (или лучше взять дефолтный) и настроить конфиг чекстайла, чтобы он принимал код автоформатированный.

2018-04-26 17:33 UTC, merged