РК №3
java-park-mail-ru/RHA-02-2018 pull request #3
Opened 2018-05-03 09:31 UTC by BritikovKI

2018-05-03 11:46 UTC, KSolovyev requested changes
Удалить закоментированный код. Очень сложно читать. 
Дальше буду смотреть, когда подключите checkstyle и поправите все ошибки

2018-05-03 11:46 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/GameMechanicsImpl.java
> +//    private final GameInitService gameInitService;
?

2018-05-03 11:46 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/GameMechanicsImpl.java
> +    public void Step(@NotNull String user, @NotNull ClientStep clientStep) {
а почему  с большой буквы?

2018-05-03 11:46 UTC, KSolovyev commented on pom.xml
>      <build>
нужно подключить checkstyle plugin и поправить все замечания

2018-05-07 20:58 UTC, KSolovyev requested changes
бинари с картинками попали в ветку. Так и планировалось?

2018-05-07 20:58 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/game/TacticalMap.java
> +        map.add(new Hex(1, 2000, Arrays.asList(2, 3), 1));
Давайте сразу будем задавать исходную карту в json. Можно пока захардкоженную

2018-05-07 20:58 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/MechanicsExecutor.java
> +        while (true) {
Договорились, вроде, попытаться сделать без тиков

2018-05-13 15:02 UTC, BritikovKI commented
PS: Да , картинки в ветке так как есть картинка которая выставляется всем по дефолту.

2018-05-21 20:07 UTC, KSolovyev requested changes

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/GameSession.java
> +             ) {
вот здесь перенесите обратно

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/GameSession.java
> +            for (Hex foR:ever) {
что такое foR?

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/MechanicsExecutor.java
> +    public void run() {
а зачем вообще нужен этот класс?

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/game/Hex.java
> +    private List<List<Integer>> neibours = new ArrayList<>();
neighbour или neighbor

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/services/ClientStepService.java
> +                    * (1 - Config.MOVING_UNITS_COEFF)));
содержимое if'а вынести в функцию

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/services/ClientStepService.java
> +            if (victoryProbability * 100 > randomToken) {
содержимое if'а в функцию

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/services/ClientStepService.java
> +            } else {
содержимое else в функцию

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/services/ClientStepService.java
> +                    if (gameSession.getMap().getMap().get(retreatHex.get(0)).get(retreatHex.get(1))
а можно порефакторить классы так, что бы это выглядело, как 
`gameSession.getMap().get(retreatHex.get(0), retreatHex.get(1))`

2018-05-21 20:07 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/game/Hex.java
> +    public List<List<Integer>> getNeibours() {
Не совсем понятно, что это, но я бы сказал, что такая функция должна быть в Tactical Map

2018-05-22 16:04 UTC, BritikovKI commented
По поводу Neighbours, они лежат в Hex, так что не имеет разницы где использовать  getNeighbours, но описать эту функцию в TacticalMap все равно прийдется через функцию в Hex

2018-05-23 13:49 UTC, KSolovyev commented
Я как раз по поводу того, что соседи не должны жить в хексе. Их надо доставать, через хекс и полную карту

2018-05-23 19:30 UTC, BritikovKI commented
я уже пытался так сделать, но это не оптимально, так как при каждой выигрышной атаке с одного хекса на другой будут просчитываться соседи на обороняемом, а сейчас они просчитываются заранее один раз,для всех хексов сразу.

2018-05-24 18:00 UTC, KSolovyev requested changes

2018-05-24 18:00 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/services/ClientStepService.java
> +    private void attackV(Hex toHex, Hex fromHex, GameSession gameSession,
attackV - непонятно, что это значит

2018-05-27 20:35 UTC, KSolovyev requested changes
Давайте доведем до какого-нибудь более-менее стабильного состояния и замержим

2018-05-27 20:35 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/GameMechanicsImpl.java
> +            if (LOGGER.isDebugEnabled()) {
такую проверку можно не делать, а сразу писать в дебаг. Внтури логгера есть такая логика

2018-05-27 20:35 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/GameMechanicsImpl.java
> +                waiters.get(0).add(user);
предлагаю вам для защиты сделать специальную версию вашей игры, где можно будет биться только 1 на 1. У вас и так будет не очень много пользователей, если они еще и по разным очередям разобьются, то очень многие просто не смогут сыграть из-за отсутствия соперника. Это совет, решать вам

2018-05-27 20:35 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/services/ClientStepService.java
> +
а чего так много пробелов-то? По конвенции должен быть 1 или 2

2018-05-27 20:35 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/websocket/Message.java
> +//import com.gameapi.rha.mechanics.messages.inbox.JoinGame;
Поубирайте закомментированный код, пожалуйста

2018-05-28 20:21 UTC, BritikovKI commented
По поводу игроков, я думаю стоит оставить режим для трех игроков, а для четырех мы точно делать не будем. Все остальные замечания вроде поправил.

2018-05-29 19:21 UTC, KSolovyev commented
Работу с тредами давайте оставим для 4 рк. А здесь конечную версию 3рк

2018-05-29 19:58 UTC, BritikovKI commented
а там до тредов все замечания поправлены

2018-05-29 20:33 UTC, KSolovyev commented
ок, но коммиты надо перенести в ветку для рк4

2018-05-30 13:17 UTC, BritikovKI commented
сделаем,но только какэто сделать?

2018-05-30 21:04 UTC, KSolovyev commented
Любым способом. Например, сделать новую ветку рк4 на месте рк3. рк3 ресетнуть на нужный коммит с хардом

2018-05-31 08:31 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/services/TurnTimerService.java
> +        thread = new Thread(this, "Поток-таймер");
неа, не пойдет. У вас на 1 игру используется 1 поток. Это слишком расточительно. Нужно решение с 1 потоком. В крайнем случае с количеством потоков равным количеству потоков томката

2018-05-31 09:36 UTC, BritikovKI commented
Все откатил, замечания к 4-му рк прийму к сведению.

2018-05-31 09:56 UTC, KSolovyev requested changes

2018-05-31 09:56 UTC, KSolovyev commented on src/test/java/com/gameapi/rha/websocket/MessageSerializationTest.java
> +//package com.gameapi.rha.websocket;
если не будете чинить, то давайте уберем

2018-05-31 09:56 UTC, KSolovyev commented on src/test/java/com/gameapi/rha/websocket/MessageSerializationTest.java
> +//package com.gameapi.rha.websocket;
а то закомментированный файл смотрится странно

2018-05-31 09:59 UTC, KSolovyev requested changes

2018-05-31 09:59 UTC, KSolovyev commented on src/main/java/com/gameapi/rha/mechanics/services/ClientStepService.java
> +
и уберите все-таки пробелы

2018-05-31 10:15 UTC, BritikovKI commented
Есть

2018-05-31 17:38 UTC, merged